# Domain-based Model Routing Configuration
# Each model gets its own subdomain for clean API separation
# Example: https://granite.your-domain.com/v1/chat/completions
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: inference-gateway
  namespace: llm
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      hostname: "*.apps.prod.rhoai.rh-aiservices-bu.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls-secret
    - name: http
      hostname: "*.apps.prod.rhoai.rh-aiservices-bu.com"
      port: 80
      protocol: HTTP
---
# HTTPRoute for Granite Model - Domain-based routing
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: granite-hostname-route
  namespace: llm
  labels:
    kuadrant.io/gateway: inference-gateway
spec:
  parentRefs:
    - name: inference-gateway
      namespace: llm
  hostnames:
    - "granite-3-3-8b-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: granite-8b-code-instruct-128k-predictor
          port: 80
          weight: 100
---
# HTTPRoute for Simulator - Domain-based routing
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simulator-hostname-route
  namespace: llm
  labels:
    kuadrant.io/gateway: inference-gateway
spec:
  parentRefs:
    - name: inference-gateway
      namespace: llm
  hostnames:
    - "simulator-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: vllm-simulator-predictor
          port: 80
          weight: 100
---
# HTTPRoute for Qwen3 Model - Domain-based routing
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qwen3-hostname-route
  namespace: llm
  labels:
    kuadrant.io/gateway: inference-gateway
spec:
  parentRefs:
    - name: inference-gateway
      namespace: llm
  hostnames:
    - "qwen3-0-6b-instruct-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qwen3-0-6b-instruct-predictor
          port: 80
          weight: 100