---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-realm-config
  namespace: keycloak-system
data:
  maas-realm.json: |
    {
      "realm": "maas",
      "enabled": true,
      "displayName": "Models as a Service",
      "accessTokenLifespan": 3600,
      "refreshTokenMaxReuse": 0,
      "sslRequired": "none",
      "clients": [
        {
          "clientId": "maas-client",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "maas-client-secret",
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "publicClient": false,
          "protocol": "openid-connect",
          "attributes": {
            "access.token.lifespan": "3600"
          },
          "redirectUris": ["*"],
          "webOrigins": ["*"]
        }
      ],
      "groups": [
        {
          "name": "free-users",
          "path": "/free-users",
          "attributes": {
            "tier": ["free"],
            "rate-limit": ["5"]
          }
        },
        {
          "name": "premium-users", 
          "path": "/premium-users",
          "attributes": {
            "tier": ["premium"],
            "rate-limit": ["20"]
          }
        },
        {
          "name": "enterprise-users",
          "path": "/enterprise-users", 
          "attributes": {
            "tier": ["enterprise"],
            "rate-limit": ["100"]
          }
        }
      ],
      "users": [
        {
          "username": "freeuser1",
          "enabled": true,
          "email": "freeuser1@example.com",
          "firstName": "Free",
          "lastName": "User1",
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "groups": ["/free-users"],
          "attributes": {
            "tier": ["free"]
          }
        },
        {
          "username": "freeuser2", 
          "enabled": true,
          "email": "freeuser2@example.com",
          "firstName": "Free",
          "lastName": "User2",
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "groups": ["/free-users"],
          "attributes": {
            "tier": ["free"]
          }
        },
        {
          "username": "premiumuser1",
          "enabled": true,
          "email": "premiumuser1@example.com", 
          "firstName": "Premium",
          "lastName": "User1",
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "groups": ["/premium-users"],
          "attributes": {
            "tier": ["premium"]
          }
        },
        {
          "username": "premiumuser2",
          "enabled": true,
          "email": "premiumuser2@example.com",
          "firstName": "Premium", 
          "lastName": "User2",
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "groups": ["/premium-users"],
          "attributes": {
            "tier": ["premium"]
          }
        },
        {
          "username": "enterpriseuser1",
          "enabled": true,
          "email": "enterpriseuser1@example.com",
          "firstName": "Enterprise",
          "lastName": "User1", 
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "groups": ["/enterprise-users"],
          "attributes": {
            "tier": ["enterprise"]
          }
        }
      ],
      "protocolMappers": [
        {
          "name": "groups",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-group-membership-mapper",
          "consentRequired": false,
          "config": {
            "full.path": "false",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "groups",
            "userinfo.token.claim": "true"
          }
        },
        {
          "name": "tier",
          "protocol": "openid-connect", 
          "protocolMapper": "oidc-usermodel-attribute-mapper",
          "consentRequired": false,
          "config": {
            "user.attribute": "tier",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "tier",
            "userinfo.token.claim": "true"
          }
        }
      ]
    }