# Istio Gateway for external traffic
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kuadrant-gateway
  namespace: llm
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "localhost"
      port: 80
      protocol: HTTP
---
# Deploy Istio Ingress Gateway for the Gateway API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuadrant-gateway-istio
  namespace: llm
  labels:
    app: kuadrant-gateway-istio
    istio: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuadrant-gateway-istio
      istio: gateway
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        sidecar.istio.io/inject: "true"
      labels:
        app: kuadrant-gateway-istio
        istio: gateway
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
      - name: istio-proxy
        image: auto
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: kuadrant-gateway-istio
  namespace: llm
  labels:
    app: kuadrant-gateway-istio
    istio: gateway
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: kuadrant-gateway-istio
    istio: gateway