# Rate limiting policies for the models
---
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: granite-rate-limit
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: granite-route
  limits:
    "requests-per-minute":
      rates:
        - limit: 100
          duration: 1m
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
      when:
        - operator: eq
          selector: auth.identity.sub
          value: ""
    "requests-per-hour":
      rates:
        - limit: 1000
          duration: 1h
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
---
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: mistral-rate-limit
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mistral-route
  limits:
    "requests-per-minute":
      rates:
        - limit: 50
          duration: 1m
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
    "requests-per-hour":
      rates:
        - limit: 500
          duration: 1h
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
---
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: qwen-rate-limit
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: qwen-route
  limits:
    "requests-per-minute":
      rates:
        - limit: 150
          duration: 1m
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
    "requests-per-hour":
      rates:
        - limit: 1500
          duration: 1h
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
---
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  name: nomic-rate-limit
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: nomic-route
  limits:
    "requests-per-minute":
      rates:
        - limit: 200
          duration: 1m
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub
    "requests-per-hour":
      rates:
        - limit: 2000
          duration: 1h
          unit: request
      counters:
        - metadata.filter_metadata.envoy\.common\.jwt.sub