# Authentication policies using existing Keycloak (DEPRECATED - use 08-auth-policies-apikey.yaml instead)
---
apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: models-auth-policy
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: granite-route
  rules:
    authentication:
      "keycloak-jwt":
        jwt:
          issuerUrl: "http://localhost:8080/auth/realms/maas"  # Local Keycloak URL
        credentials:
          authorizationHeader:
            prefix: Bearer
    authorization:
      "api-access":
        when:
          - selector: auth.identity.realm_access.roles
            operator: incl
            value: "api-user"
    response:
      success:
        headers:
          "x-user-id":
            selector: auth.identity.sub
          "x-user-email":
            selector: auth.identity.email
---
# Apply same auth policy to Mistral route
apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: mistral-auth-policy
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: mistral-route
  rules:
    authentication:
      "keycloak-jwt":
        jwt:
          issuerUrl: "http://localhost:8080/auth/realms/maas"  # Local Keycloak URL
        credentials:
          authorizationHeader:
            prefix: Bearer
    authorization:
      "api-access":
        when:
          - selector: auth.identity.realm_access.roles
            operator: incl
            value: "api-user"
    response:
      success:
        headers:
          "x-user-id":
            selector: auth.identity.sub
          "x-user-email":
            selector: auth.identity.email
---
# Apply same auth policy to Nomic route
apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: nomic-auth-policy
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: nomic-route
  rules:
    authentication:
      "keycloak-jwt":
        jwt:
          issuerUrl: "http://localhost:8080/auth/realms/maas"  # Local Keycloak URL
        credentials:
          authorizationHeader:
            prefix: Bearer
    authorization:
      "api-access":
        when:
          - selector: auth.identity.realm_access.roles
            operator: incl
            value: "api-user"
    response:
      success:
        headers:
          "x-user-id":
            selector: auth.identity.sub
          "x-user-email":
            selector: auth.identity.email