# Gateway-level Rate Limiting Policy
# This single policy applies to all routes through the gateway
# Based on working configuration with tiered user groups
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gateway-rate-limits
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  limits:
    free-user-requests:
      rates:
        - limit: 5
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "free")
      counters:
        - expression: auth.identity.userid
    premium-user-requests:
      rates:
        - limit: 20
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "premium")
      counters:
        - expression: auth.identity.userid
    enterprise-user-requests:
      rates:
        - limit: 50
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "enterprise")
      counters:
        - expression: auth.identity.userid
