# EXAMPLE: Tiered Rate Limiting with User Groups
# This is a working example provided by the user for implementing tiered rate limiting
# based on user groups (free vs premium). Use this as reference when implementing 
# rate limiting policies.

###############################################################################
# API-KEY SECRETS - Tiered API keys for free and premium users
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: freeuser1-apikey
  namespace: llm
  labels:
    kuadrant.io/auth-secret: "true"
    app: llm-gateway
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: freeuser1
stringData:
  api_key: freeuser1_key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: freeuser2-apikey
  namespace: llm
  labels:
    kuadrant.io/auth-secret: "true"
    app: llm-gateway
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: freeuser2
stringData:
  api_key: freeuser2_key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: premiumuser1-apikey
  namespace: llm
  labels:
    kuadrant.io/auth-secret: "true"
    app: llm-gateway
  annotations:
    kuadrant.io/groups: premium
    secret.kuadrant.io/user-id: premiumuser1
stringData:
  api_key: premiumuser1_key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: premiumuser2-apikey
  namespace: llm
  labels:
    kuadrant.io/auth-secret: "true"
    app: llm-gateway
  annotations:
    kuadrant.io/groups: premium
    secret.kuadrant.io/user-id: premiumuser2
stringData:
  api_key: premiumuser2_key
type: Opaque

###############################################################################
# AUTHPOLICY - API-key authentication with user and group extraction
###############################################################################
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: api-key-auth-with-groups
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: vllm-gateway
  rules:
    authentication:
      api-key-users:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: llm-gateway
        credentials:
          authorizationHeader:
            prefix: APIKEY
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
                groups:
                  selector: auth.identity.metadata.annotations.kuadrant\.io/groups
    authorization:
      allow-groups:
        opa:
          rego: |
            groups := split(object.get(input.auth.identity.metadata.annotations, "kuadrant.io/groups", ""), ",")
            allow { groups[_] == "free" }
            allow { groups[_] == "premium" }

###############################################################################
# RATELIMITPOLICY - Tiered rate limiting based on user groups
###############################################################################
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: basic-rate-limits
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: vllm-gateway
  limits:
    free-user-requests:
      rates:
        - limit: 2
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "free")
      counters:
        - expression: auth.identity.userid
    premium-user-requests:
      rates:
        - limit: 10
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "premium")
      counters:
        - expression: auth.identity.userid