# Kustomization for Complete MaaS Deployment
# Deploys all components for Models-as-a-Service platform
# Use: kubectl apply -k .

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: maas-deployment

# Deploy modular components using sub-kustomizations
  # Base infrastructure (namespaces, operators, storage)
  
  # Gateway and routing configuration  
  
  # Authentication and rate limiting
  
  # Observability stack (Prometheus, Grafana, dashboards)
resources:
- kustomize/base
- kustomize/gateway
- kustomize/auth
- kustomize/observability

# Configuration patches
  # Ensure consistent namespace
  
  # Ensure HTTPRoutes point to correct gateway namespace
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: llm
  target:
    kind: Gateway
    name: inference-gateway
- patch: |-
    - op: replace
      path: /spec/parentRefs/0/namespace
      value: llm
  target:
    kind: HTTPRoute

# Common labels for all resources

# Common annotations
commonAnnotations:
  config.kubernetes.io/origin: |
    path: deployment/kuadrant/kustomization.yaml
  documentation: https://github.com/your-org/models-aas

# Images that can be customized
images:
- name: kuadrant-operator
  newTag: latest
- name: limitador
  newTag: latest
- name: authorino
  newTag: latest

# Configuration for different environments
configMapGenerator:
- literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=info
  - ENABLE_DEBUG=false
  name: deployment-config
  options:
    disableNameSuffixHash: true

# Deployment replicas (can be overridden per environment)
replicas:
- count: 1
  name: kuadrant-operator-controller-manager
- count: 1
  name: limitador-limitador
- count: 1
  name: authorino
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maas-platform
    app.kubernetes.io/part-of: kuadrant-maas
