# Kustomization for Complete MaaS Deployment
# Deploys all components for Models-as-a-Service platform
# Use: kubectl apply -k .

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-deployment
  annotations:
    config.kubernetes.io/local-config: "true"

# Namespace for all resources
namespace: llm

# Create namespace if it doesn't exist
resources:
  # Core Infrastructure
  - 00-namespaces.yaml
  - 01-kserve-config.yaml
  - 04-kuadrant-operator.yaml
  - 03-kuadrant-instance.yaml
  
  # Storage
  - minio-local-storage.yaml
  
  # Gateway and Routing
  - 02-gateway-configuration.yaml
  - 03-model-routing-domains.yaml
  
  # Authentication and Rate Limiting
  - 05-api-key-secrets.yaml
  - 06-auth-policies-apikey.yaml
  - 07-rate-limit-policies.yaml
  
  # Observability
  - 08-observability.yaml
  - 09-monitoring-dashboard.yaml

# Configuration patches
patches:
  # Ensure consistent namespace
  - target:
      kind: Gateway
      name: kuadrant-gateway
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: llm
  
  # Ensure HTTPRoutes point to correct gateway namespace
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/namespace
        value: llm

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: maas-platform
  app.kubernetes.io/part-of: kuadrant-maas
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  config.kubernetes.io/origin: |
    path: deployment/kuadrant/kustomization.yaml
  documentation: "https://github.com/your-org/models-aas"

# Images that can be customized
images:
  - name: kuadrant-operator
    newTag: latest
  - name: limitador
    newTag: latest
  - name: authorino
    newTag: latest

# Configuration for different environments
configMapGenerator:
  - name: deployment-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - ENABLE_DEBUG=false
    options:
      disableNameSuffixHash: true

# Deployment replicas (can be overridden per environment)
replicas:
  - name: kuadrant-operator-controller-manager
    count: 1
  - name: limitador-limitador
    count: 1
  - name: authorino
    count: 1