apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: models-aas-observability
  labels:
    app: models-aas-observability
spec:
  image: quay.io/prometheus/prometheus:v2.22.1
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: models-aas-observability
  version: v2.22.1
  serviceMonitorSelector: {}
---
apiVersion: v1
kind: Service
metadata:
  name: models-aas-observability
  labels:
    app: models-aas-observability
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: models-aas-observability
  sessionAffinity: ClientIP