---
# Qwen3-0.6B Model serving with vLLM
# Small but capable model perfect for testing GPU serving
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Qwen3-0.6B-Instruct
    serving.kserve.io/deploymentMode: RawDeployment
  name: qwen3-0-6b-instruct
  namespace: llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      modelUri: hf://Qwen/Qwen2.5-0.5B-Instruct  # Using the more stable 2.5 variant
      resources:
        limits:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 4Gi
          nvidia.com/gpu: '1'
      runtime: vllm-2.12-6144
      env:
        - name: HF_TOKEN
          value: ""  # Add your HF token here if needed for private models
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists