apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-gateway
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: llm

resources:
  # Gateway and Routing
  - ../../02-gateway-configuration.yaml
  - ../../03-model-routing-domains.yaml

commonLabels:
  app.kubernetes.io/name: maas-platform
  app.kubernetes.io/part-of: kuadrant-maas
  app.kubernetes.io/component: gateway
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  config.kubernetes.io/origin: |
    path: deployment/kuadrant/kustomize/gateway/kustomization.yaml

# Configuration patches
patches:
  # Ensure consistent namespace
  - target:
      kind: Gateway
      name: inference-gateway
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: llm
  
  # Ensure HTTPRoutes point to correct gateway namespace
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/namespace
        value: llm